### ISSUE TITLE
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_mapped'

### ISSUE THREAD

**Issue by YuanQing-KIB** [yeeus/GCI#13]
Hello, When I used the GCI software to assemble my T2T genome, the following error occurred. What happened?

Used arguments:{'reference': '/export/home/zzl/YQ/Genome/Mel.genome.fa', 'hifi': ['/export/home/zzl/YQ/Genome/04-GCI/Mel.hifi.bam', '/export/home/zzl/YQ/Genome/04-GCI/Mel.hifi.paf'], 'nano': ['/export/home/zzl/YQ/Genome/04-GCI/Mel.ont.bam', '/export/home/zzl/YQ/Genome/04-GCI/Mel.ont.paf'], 'chrs': None, 'regions': None, 'threshold': 0, 'dist_percent': 0.005, 'threads': 20, 'directory': '/export/home/zzl/YQ/Genome/04-GCI/Mel.GCI.out', 'prefix': 'Mel', 'map_qual': 30, 'mq_cutoff': 50, 'iden_percent': 0.9, 'ovlp_percent': 0.9, 'clip_percent': 0.1, 'flank_len': 15, 'plot': True, 'depth_min': 0.1, 'depth_max': 4.0, 'window_size': 50000, 'image_type': 'pdf', 'force': False}
Finding gaps ...
Finding gaps done!!! Awesome! No gaps were found!

Filtering HiFi alignment files ...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/export/software/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/export/software/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GCI.py", line 152, in read_sam
    if (segment.is_mapped == True) and (segment.is_secondary == False) and (segment.is_supplementary == False) and (segment.mapping_quality >= map_qual):
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_mapped'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GCI.py", line 1107, in <module>
    GCI(**args)
  File "GCI.py", line 1008, in GCI
    hifi_depths, targets_length = filter(hifi_paf, hifi_bam, prefix+'_hifi', map_qual, mq_cutoff, iden_percent, clip_percent, ovlp_percent, flank_len, directory, force, 'HiFi', chrs_list, threads)
  File "GCI.py", line 262, in filter
    for tmp_samfile_dict, tmp_high_qual_querys in pool.map(read_sam, tasks):
  File "/export/software/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/export/software/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'pysam.libcalignedsegment.AlignedSegment' object has no attribute 'is_mapped'

**Comment by yeeus** [comment]
I think it was the problem of your version of `pysam` as discussed in issue #9 
Please check your `pysam` verison with `pip show pysam` and if it's not the lastest please update it.

**Comment by YuanQing-KIB** [comment]
Thank you very much. I'll try

**Comment by chenys1998** [comment]
I also met this error. 
As shown in logfile, error is occurred in GCI.py line 152.
**if (segment.is_mapped == True)  …**
 
Maybe in some pysam version, "is_mapped" is not accessible.（The version I used is 0.17.0）
But in this version, "is_unmapped" is accessible.

So i changed GCI.py line 152 to:
 **if (segment.is_unmapped == False)  …**
And soft can run normally.

**Comment by yeeus** [comment]
@chenys1998 thank you every much for reporting this. I have fixed this in the lastest commit.

**Comment by yeeus** [comment]
Close due to long time inactivity.
